# git:
#   paging:
#     pager: delta --paging=never

git:
  pagers:
    - pager: delta --paging=never

gui:
  expandFocusedSidePanel: true
  showRandomTip: false
  border: single
  filterMode: fuzzy
  disableStartupPopups: true
  notARepository: quit
