git:
  diffRenderers:
    - name: delta
      command: delta --paging=never
    - name: delta-side-by-side
      command: delta --paging=never --side-by-side
gui:
  showRandomTip: false
  border: single
  filterMode: fuzzy
  disableStartupPopups: true
  notARepository: quit
  showBottomLine: false
  sidePanels:
    - [files]
    - [branches]
    - [commits]
keybinding:
  universal:
    cycleDiffRenderers: "="
