# git:
#   paging:
#     pager: delta --paging=never

git:
  pagers:
    - name: delta
      pager: delta --paging=never
    - name: delta-side-by-side
      pager: delta --paging=never --side-by-side

gui:
  expandFocusedSidePanel: true
  showRandomTip: false
  border: single
  filterMode: fuzzy
  disableStartupPopups: true
  notARepository: quit
  sidePanels:
    - [status]
    - [files]
    - [branches]
    - [commits]
    - [stash]

keybinding:
  universal:
    cyclePagers: "="
