FROM fedora:41

RUN dnf install -y git ruby zsh which hostname && \
    dnf clean all

ENV SHELL=/usr/bin/zsh

RUN git clone https://github.com/elanmed/dotfiles ~/.dotfiles && \
    cd ~/.dotfiles && \
    sed -i 's|git@github.com:|https://github.com/|g' .gitmodules && \
    git submodule init && \
    git submodule update

RUN cd ~/.dotfiles && ruby bootstrap.rb --package-manager=dnf --server

WORKDIR /workspace
