model: gpt-5.6-luna
# baseURL: https://opencode.ai/zen/go/v1
# baseURL: https://openrouter.ai/api/v1
baseURL: https://opencode.ai/zen/v1
contextWindowPerModel:
  deepseek-v4-flash: 1000000
  deepseek-v4-pro: 1000000
  kimi-k3: 1000000
  kimi-k2.7-code: 256000
  gpt-5.6-luna: 256000
sdkProvider: "openai"
gateway: "opencode"
pricingPerModel:
  kimi-k3:
    inputPerMillion: 3
    outputPerMillion: 15
    cacheReadPerMillion: 0.3
  kimi-k2.7-code:
    inputPerMillion: 0.95
    outputPerMillion: 4
    cacheReadPerMillion: 0.19
  deepseek-v4-pro:
    inputPerMillion: 1.74
    outputPerMillion: 3.48
    cacheReadPerMillion: 0.0145
  gpt-5.6-luna:
    inputPerMillion: 0.2
    outputPerMillion: 1.2
    cacheReadPerMillion: 0.02
    cacheWritePerMillion: 0.25
loadingStateFrames:
  - "􀂗 "
  - "􀂘 "
  - "􀂙 "
  - "􀂚 "
  - "􀂛 "
  - "􀂜 "
  - "􀂝 "
  - "􀂞 "
  - "􀂟 "
  - "􀂠 "
  - "􀂡 "
  - "􀂢 "
  - "􀂣 "
  - "􀂤 "
  - "􀂥 "
  - "􀂦 "
  - "􀂧 "
  - "􀂨 "
  - "􀂩 "
  - "􀂪 "
  - "􀂫 "
  - "􀂬 "
  - "􀂭 "
  - "􀂮 "
  - "􀂯 "
  - "􀂰 "
  - "􀂱 "
  - "􀂲 "
  - "􀂳 "
  - "􀂴 "
  - "􀂵 "
  - "􀂶 "
  - "􀂷 "
  - "􀂸 "
  - "􀂹 "
  - "􀂺 "
  - "􀂻 "
  - "􀂼 "
  - "􀂽 "
  - "􀂾 "
  - "􀂿 "
  - "􀃀 "
  - "􀃁 "
  - "􀃂 "
  - "􀃃 "
  - "􀃄 "
  - "􀃅 "
  - "􀃆 "
  - "􀃇 "
  - "􀃈 "
  - "􀃉 "
promptPrefix: "􀀀   > "
usageLimit:
  dollarAmount: 12
  duration: 5h
keymaps:
  history:
    name: "o"
    ctrl: true
  commit:
    name: "x"
    ctrl: true
