# model: glm-5.3-flash
model: gpt-6-luna
baseURL: https://opencode.ai/zen/go/v1
# baseURL: https://opencode.ai/zen/v1
contextWindowPerModel:
  kimi-k3: 1000000
  gpt-6-luna: 1050000
  glm-5.3-flash: 1300000
sdkProvider: "openai"
gateway: "opencode"
pricingPerModel:
  kimi-k3:
    inputPerMillion: 3
    outputPerMillion: 15
    cacheReadPerMillion: 0.3
  gpt-6-luna:
    inputPerMillion: 0.1
    outputPerMillion: 0.5
    cacheReadPerMillion: 0.01
    cacheWritePerMillion: 0.13
  glm-5.3-flash:
    inputPerMillion: 0.15
    outputPerMillion: 0.5
    cacheReadPerMillion: 0.03
usageLimit:
  dollarAmount: 12
  duration: 5h
compactWithStructuredOutput: false
# abcdefghijklmnopqrstuvwxyz
# ------------m---q----v---z used by the os
# a-cde--hi----------------- used by native readline
# a-cde--hi---m---q----v---z used
# -b---fg--jkl-nop-rstu-wxy- available
keymaps:
  history:
    name: "t"
    ctrl: true
  paste:
    name: "v"
    ctrl: true
  commit:
    name: "o"
    ctrl: true
  lastresponse:
    name: "r"
    ctrl: true
  lastmessage:
    name: "s"
    ctrl: true
  lastdiff:
    name: "x"
    ctrl: true
  editpage:
    name: "f"
    ctrl: true
promptPrefix: "􀀀   > "
loadingStateFrames:
  - "􀂗  "
  - "􀂘  "
  - "􀂙  "
  - "􀂚  "
  - "􀂛  "
  - "􀂜  "
  - "􀂝  "
  - "􀂞  "
  - "􀂟  "
  - "􀂠  "
  - "􀂡  "
  - "􀂢  "
  - "􀂣  "
  - "􀂤  "
  - "􀂥  "
  - "􀂦  "
  - "􀂧  "
  - "􀂨  "
  - "􀂩  "
  - "􀂪  "
  - "􀂫  "
  - "􀂬  "
  - "􀂭  "
  - "􀂮  "
  - "􀂯  "
  - "􀂰  "
  - "􀂱  "
  - "􀂲  "
  - "􀂳  "
  - "􀂴  "
  - "􀂵  "
  - "􀂶  "
  - "􀂷  "
  - "􀂸  "
  - "􀂹  "
  - "􀂺  "
  - "􀂻  "
  - "􀂼  "
  - "􀂽  "
  - "􀂾  "
  - "􀂿  "
  - "􀃀  "
  - "􀃁  "
  - "􀃂  "
  - "􀃃  "
  - "􀃄  "
  - "􀃅  "
  - "􀃆  "
  - "􀃇  "
  - "􀃈  "
  - "􀃉  "
