FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y git zsh sudo curl apt-utils && \
    apt-get clean

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
ENV SHELL=/usr/bin/zsh

RUN git clone https://github.com/elanmed/dotfiles "$HOME/.dotfiles" && \
    cd ~/.dotfiles && \
    sed -i 's|git@github.com:|https://github.com/|g' .gitmodules

RUN cd ~/.dotfiles && bash bootstrap.sh -p apt -d headless
