FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y git zsh sudo curl apt-utils && \
    apt-get clean

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
ENV SHELL=/usr/bin/zsh

RUN git clone https://github.com/elanmed/dotfiles ~/.dotfiles && \
    cd ~/.dotfiles && \
    sed -i 's|git@github.com:|https://github.com/|g' .gitmodules && \
    git submodule init && \
    git submodule update

RUN cd ~/.dotfiles && bash bootstrap.sh --package-manager apt --container
ENV PATH="/root/.local/bin:$PATH"
RUN curl -fsSL https://claude.ai/install.sh | bash
# new copy per container since claude appends to this file
RUN cp -r ~/.dotfiles/containers/.claude/. ~/.claude
RUN cp ~/.dotfiles/containers/.claude.json ~/.claude.json
