FROM fedora:42

RUN dnf install -y git ruby zsh which hostname libatomic 'dnf-command(copr)' && \
    dnf copr enable -y dejan/lazygit && \
    dnf clean all

ENV SHELL=/usr/bin/zsh

RUN git clone https://github.com/elanmed/dotfiles ~/.dotfiles && \
    cd ~/.dotfiles && \
    sed -i 's|git@github.com:|https://github.com/|g' .gitmodules && \
    git submodule init && \
    git submodule update

RUN cd ~/.dotfiles && bash bootstrap.sh --package-manager dnf --server
RUN curl -fsSL https://claude.ai/install.sh | bash
# new copy per container since claude appends to this file
RUN cp -r ~/.dotfiles/containers/.claude/. ~/.claude
RUN cp ~/.dotfiles/containers/.claude.json ~/.claude.json

