FROM fedora:42

RUN dnf install -y git ruby zsh which hostname 'dnf-command(copr)' && \
    dnf copr enable -y dejan/lazygit && \
    dnf clean all

ENV SHELL=/usr/bin/zsh

# TODO: test
RUN useradd -m -s /usr/bin/zsh -G wheel containeruser
RUN echo 'containeruser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER containeruser

RUN git clone https://github.com/elanmed/dotfiles ~/.dotfiles && \
    cd ~/.dotfiles && \
    sed -i 's|git@github.com:|https://github.com/|g' .gitmodules && \
    git submodule init && \
    git submodule update

RUN cd ~/.dotfiles && ruby bootstrap.rb --package-manager=dnf --server --skip-nvim
RUN curl -fsSL https://claude.ai/install.sh | bash
# new copy per container since claude appends to this file
RUN cp -r ~/.dotfiles/containers/.claude/. ~/.claude
RUN cp ~/.dotfiles/containers/.claude.json ~/.claude.json

