# https://spaceship-prompt.sh/config/intro/
SPACESHIP_PROMPT_ORDER=(
  dir 
  git 
  node
  exit_code 
  exec_time 
  char
)

SPACESHIP_DIR_COLOR="yellow"
SPACESHIP_DIR_TRUNC_REPO=false

SPACESHIP_GIT_STATUS_STASHED=""

SPACESHIP_EXIT_CODE_SYMBOL=""
SPACESHIP_EXIT_CODE_PREFIX="status code: "
SPACESHIP_EXIT_CODE_SHOW=true

SPACESHIP_CHAR_SYMBOL=" "
SPACESHIP_CHAR_SUFFIX="\n🚀:: "

SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_ASYNC=false
