FROM fedora:43

RUN dnf install -y git zsh which hostname libatomic nc openssl SDL2 glib2 pixman zlib alsa-lib pulseaudio-libs libpng && \
    dnf clean all

ENV SHELL=/usr/bin/zsh

RUN git clone https://github.com/elanmed/dotfiles ~/.dotfiles && \
    cd ~/.dotfiles && \
    sed -i 's|git@github.com:|https://github.com/|g' .gitmodules

RUN cd ~/.dotfiles && bash bootstrap.sh -p dnf -d headless
RUN . ~/.dotfiles/nvm/.nvm/nvm.sh && nvm install --lts
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    ~/.local/bin/uv tool install pebble-tool && \
    . ~/.dotfiles/nvm/.nvm/nvm.sh && ~/.local/bin/pebble sdk install latest
